#!/usr/bin/env sh

monitor1=eDP-1
#monitor2=DP-1

#REDSHIFT
killall -q redshift;
while pgrep -x redshift >/dev/null; do sleep 1; done
redshift -P &

#COMPTON
killall -q picom
while pgrep -x picom >/dev/null; do sleep 1; done
picom --config ~/.config/picom.conf -b &

# DUNST
killall -q dunst
while pgrep -x dunst >/dev/null; do sleep 1; done
dunst -config /home/pyska/.config/dunst/dunstrc &

# PIPEWIRE
gentoo-pipewire-launcher restart &

# POLYBAR
sleep 0.5
killall -q waybar
while pgrep -x waybar >/dev/null; do sleep 0.5; done
MONITOR=$monitor1 waybar &

